- id: copyright-fixer
  name: copyright fixer
  description: prevents files without copyright notices from being added.
  entry: copyright_fixer
  language: python
  stages: [pre-commit]
  types: [text]
